const beginPattern = [
  // Add new patterns for higher difficulty here
  [
     {
      positionX: 0,
      positionY: 1,
      positionZ: -160,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -165,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -170,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -175,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -180,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -100,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -105,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -110,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -115,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -120,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -60,
      obstacleName: 'Coin',
      type: 'coin',
    },
     {
      positionX: 0,
      positionY: 1,
      positionZ: -65,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -70,
      obstacleName: 'Coin',
      type: 'coin',
    },
     {
      positionX: 0,
      positionY: 1,
      positionZ: -75,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -80,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -85,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -110,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -115,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -120,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -125,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -130,
      obstacleName: 'Coin',
      type: 'coin',
    },
  ],
];

export default beginPattern;
