const patterns1 = [
   //Pillars ------------------------------------------------------------------------------------------
//Pilar Middle
  [
      {
      positionX: 0,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'FloorFoundation',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 4,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 20,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 2,
      positionZ: -280,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 2,
      positionZ: -270,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 2,
      positionZ: -260,
      obstacleName: 'Coin',
      type: 'coin',
    }
  ],
  //Pilar Right
  [
    {
      positionX: 5,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'FloorFoundation',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 4,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 20,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 2,
      positionZ: -280,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 2,
      positionZ: -270,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 2,
      positionZ: -260,
      obstacleName: 'Coin',
      type: 'coin',
    },
  
  ],
  //Pilar Left
  [
    {
      positionX: -5,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'FloorFoundation',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 4,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 20,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 2,
      positionZ: -280,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 2,
      positionZ: -270,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 2,
      positionZ: -260,
      obstacleName: 'Coin',
      type: 'coin',
    },
  
  ],
  //Pilar Middle with right jump
  [
      {
      positionX: 0,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'FloorFoundation',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 4,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 20,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -7,
      positionY: -8,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3.5, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 4,
      positionZ: -286,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 6,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 8,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 9,
      positionZ: -308,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 8,
      positionZ: -316,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 6,
      positionZ: -324,
      obstacleName: 'Coin',
      type: 'coin',
    },
  

  ],
  //Pillar Middle with Left jump
  [
      {
      positionX: 0,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'FloorFoundation',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 4,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 20,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 7,
      positionY: -8,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3.5, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 4,
      positionZ: -286,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 6,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 8,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 9,
      positionZ: -308,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 8,
      positionZ: -316,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 6,
      positionZ: -324,
      obstacleName: 'Coin',
      type: 'coin',
    },
  

  ],
  //Pillar middle with left and right jumps (coins left)
  [
      {
      positionX: 0,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'FloorFoundation',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 4,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 20,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -7,
      positionY: -8,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3.5, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 7,
      positionY: -8,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3.5, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 4,
      positionZ: -286,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 6,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 8,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 9,
      positionZ: -308,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 8,
      positionZ: -316,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 6,
      positionZ: -324,
      obstacleName: 'Coin',
      type: 'coin',
    },
  

  ],
  //Pillar middle with left and right jumps (coins right)
  [
      {
      positionX: 0,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'FloorFoundation',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 4,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 20,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -7,
      positionY: -8,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3.5, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 7,
      positionY: -8,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3.5, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 4,
      positionZ: -286,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 6,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 8,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 9,
      positionZ: -308,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 8,
      positionZ: -316,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 6,
      positionZ: -324,
      obstacleName: 'Coin',
      type: 'coin',
    },
  

  ],
    
  
  //Pillar right with jumps (coins right)
   [
      {
      positionX: -5,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'FloorFoundation',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 4,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 20,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -10,
      positionY: -8,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 10,
      positionY: -8,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -8,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3.5, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 7,
      positionY: -8,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3.5, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 4,
      positionZ: -286,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 6,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 8,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 9,
      positionZ: -308,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 8,
      positionZ: -316,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 6,
      positionZ: -324,
      obstacleName: 'Coin',
      type: 'coin',
    },
  
  ],
  //Pillar right with jumps (coins right)
   [
      {
      positionX: -5,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'FloorFoundation',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 4,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 20,
      positionZ: -300,
      obstacleName: 'Pillar',
      scale: [2, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -10,
      positionY: -8,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 10,
      positionY: -8,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -8,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3.5, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 7,
      positionY: -8,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3.5, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 4,
      positionZ: -286,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 8,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 9,
      positionZ: -308,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 8,
      positionZ: -316,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -324,
      obstacleName: 'Coin',
      type: 'coin',
    },
  
  ],
  //Pillar Left with jumps (coins left)
    [
        {
        positionX: 5,
        positionY: 0,
        positionZ: -300,
        obstacleName: 'FloorFoundation',
        type: 'obstacle',
      },
      {
        positionX: 5,
        positionY: 4,
        positionZ: -300,
        obstacleName: 'Pillar',
        scale: [2, 4, 2],
        type: 'obstacle',
      },
      {
        positionX: 5,
        positionY: 20,
        positionZ: -300,
        obstacleName: 'Pillar',
        scale: [2, 4, 2],
        type: 'obstacle',
      },
      {
        positionX: -10,
        positionY: -8,
        positionZ: -300,
        obstacleName: 'WallFlat',
        scale: [3, 3, 3],
        type: 'obstacle',
      },
      {
        positionX: 10,
        positionY: -8,
        positionZ: -300,
        obstacleName: 'WallFlat',
        scale: [3, 3, 3],
        type: 'obstacle',
      },
      {
        positionX: 0,
        positionY: -8,
        positionZ: -300,
        obstacleName: 'WallFlat',
        scale: [3.5, 3, 3],
        type: 'obstacle',
      },
      {
        positionX: 7,
        positionY: -8,
        positionZ: -300,
        obstacleName: 'WallFlat',
        scale: [3.5, 3, 3],
        type: 'obstacle',
      },
      {
        positionX: -5,
        positionY: 4,
        positionZ: -286,
        obstacleName: 'Coin',
        type: 'coin',
      },
      {
        positionX: -5,
        positionY: 6,
        positionZ: -292,
        obstacleName: 'Coin',
        type: 'coin',
      },
      {
        positionX: -5,
        positionY: 8,
        positionZ: -300,
        obstacleName: 'Coin',
        type: 'coin',
      },
      {
        positionX: -5,
        positionY: 9,
        positionZ: -308,
        obstacleName: 'Coin',
        type: 'coin',
      },
      {
        positionX: -5,
        positionY: 8,
        positionZ: -316,
        obstacleName: 'Coin',
        type: 'coin',
      },
      {
        positionX: -5,
        positionY: 6,
        positionZ: -324,
        obstacleName: 'Coin',
        type: 'coin',
      },
  
      
    ],
    //Pillar Left with jumps (coins middle)
    [
        {
        positionX: 5,
        positionY: 0,
        positionZ: -300,
        obstacleName: 'FloorFoundation',
        type: 'obstacle',
      },
      {
        positionX: 5,
        positionY: 4,
        positionZ: -300,
        obstacleName: 'Pillar',
        scale: [2, 4, 2],
        type: 'obstacle',
      },
      {
        positionX: 5,
        positionY: 20,
        positionZ: -300,
        obstacleName: 'Pillar',
        scale: [2, 4, 2],
        type: 'obstacle',
      },
      {
        positionX: -10,
        positionY: -8,
        positionZ: -300,
        obstacleName: 'WallFlat',
        scale: [3, 3, 3],
        type: 'obstacle',
      },
      {
        positionX: 10,
        positionY: -8,
        positionZ: -300,
        obstacleName: 'WallFlat',
        scale: [3, 3, 3],
        type: 'obstacle',
      },
      {
        positionX: 0,
        positionY: -8,
        positionZ: -300,
        obstacleName: 'WallFlat',
        scale: [3.5, 3, 3],
        type: 'obstacle',
      },
      {
        positionX: 7,
        positionY: -8,
        positionZ: -300,
        obstacleName: 'WallFlat',
        scale: [3.5, 3, 3],
        type: 'obstacle',
      },
      {
        positionX: 0,
        positionY: 4,
        positionZ: -286,
        obstacleName: 'Coin',
        type: 'coin',
      },
      {
        positionX: 0,
        positionY: 6,
        positionZ: -292,
        obstacleName: 'Coin',
        type: 'coin',
      },
      {
        positionX: 0,
        positionY: 8,
        positionZ: -300,
        obstacleName: 'Coin',
        type: 'coin',
      },
      {
        positionX: 0,
        positionY: 9,
        positionZ: -308,
        obstacleName: 'Coin',
        type: 'coin',
      },
      {
        positionX: 0,
        positionY: 8,
        positionZ: -316,
        obstacleName: 'Coin',
        type: 'coin',
      },
      {
        positionX: 0,
        positionY: 6,
        positionZ: -324,
        obstacleName: 'Coin',
        type: 'coin',
      },
    ],
    //Walls ---------------------------------------------------------------------------------------
    [
    // Pattern muren met deur in het midden 
    {
      positionX: -9,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 9,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'WallDoorway',
      scale: [3, 3, 3],
      type: 'doorway',
    },
    {
      positionX: 0,
      positionY: 10.2,
      positionZ: -300,
      obstacleName: 'BoxTransparent',
      color: 'blue',
      scale: [6, 4, 3.2],
      type: 'obstacle',
    },
  ],
  // Pattern muren met deur rechts 
  [
    {
      positionX: -6,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [4, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'WallDoorway',
      scale: [3, 3, 3],
      type: 'doorway',
    },
    {
      positionX: 5,
      positionY: 10.2,
      positionZ: -300,
      obstacleName: 'BoxTransparent',
      color: 'blue',
      scale: [6, 4, 3.2],
      type: 'obstacle',
    },
    {
      positionX: 14,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
  ],
  // Pattern muren met deur links 
  [
    {
      positionX: 6,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [4, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'WallDoorway',
      scale: [3, 3, 3],
      type: 'doorway',
    },
    {
      positionX: -5,
      positionY: 10.2,
      positionZ: -300,
      obstacleName: 'BoxTransparent',
      color: 'blue',
      scale: [6, 4, 3.2],
      type: 'obstacle',
    },
    {
      positionX: -14,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
  ],
  // pattern met twee deuren 
  [
    {
      positionX: -5,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'WallDoorway',
      scale: [3, 3, 3],
      type: 'doorway',
    },
    {
      positionX: -5,
      positionY: 10.2,
      positionZ: -300,
      obstacleName: 'BoxTransparent',
      color: 'blue',
      scale: [6, 4, 3.2],
      type: 'obstacle',
    },
    {
      positionX: -14,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },

    {
      positionX: 5,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'WallDoorway',
      scale: [3, 3, 3],
      type: 'doorway',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'BoxTransparent',
      color: 'blue',
      scale: [3.8, 12, 3.2],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 10.2,
      positionZ: -300,
      obstacleName: 'BoxTransparent',
      color: 'blue',
      scale: [6, 4, 3.2],
      type: 'obstacle',
    },
    {
      positionX: 14,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
  ],
  // Pattern muren met 2 crouch deur rechts en links
  [ 
    {
      positionX: -11.2,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Barrier',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Barrier',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 11.2,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Barrier',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -5,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [1, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: -4.5,
      positionY: -5,
      positionZ: -300,
      obstacleName: 'WallDoorway',
      scale: [3, 3, 3],
      type: 'doorway',
    },
    {
      positionX: -4.5,
      positionY: 5.2,
      positionZ: -300,
      obstacleName: 'BoxTransparent',
      color: 'blue',
      scale: [6, 4, 3.2],
      type: 'obstacle',
    },
    {
      positionX: 4.5,
      positionY: -5,
      positionZ: -300,
      obstacleName: 'WallDoorway',
      scale: [3, 3, 3],
      type: 'doorway',
    },
    {
      positionX: 4.5,
      positionY: 5.2,
      positionZ: -300,
      obstacleName: 'BoxTransparent',
      color: 'blue',
      scale: [6, 4, 3.2],
      type: 'obstacle',
    },
    {
      positionX: -14,
      positionY: -5,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 14,
      positionY: -5,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
  ],
   [
    // pattern met muur met crouch deur midden
    {
      positionX: -11.2,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Barrier',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Barrier',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 11.2,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Barrier',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: -9,
      positionY: -5,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 9,
      positionY: -5,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -5,
      positionZ: -300,
      obstacleName: 'WallDoorway',
      scale: [3, 3, 3],
      type: 'doorway',
    },
    {
      positionX: 0,
      positionY: 5.2,
      positionZ: -300,
      obstacleName: 'BoxTransparent',
      color: 'blue',
      scale: [6, 4, 3.2],
      type: 'obstacle',
    },
  ],
  // Pattern muren met crouch deur rechts 
  [
    {
      positionX: -11.2,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Barrier',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Barrier',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 11.2,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Barrier',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: -6.5,
      positionY: -5,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [4, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 4.5,
      positionY: -5,
      positionZ: -300,
      obstacleName: 'WallDoorway',
      scale: [3, 3, 3],
      type: 'doorway',
    },
    {
      positionX: 4.5,
      positionY: 5.2,
      positionZ: -300,
      obstacleName: 'BoxTransparent',
      color: 'blue',
      scale: [6, 4, 3.2],
      type: 'obstacle',
    },
    {
      positionX: 14,
      positionY: -5,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
  ],
  // Pattern muren met crouch deur links
  {
      positionX: -11.2,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Barrier',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Barrier',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: 11.2,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Barrier',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
  [
    {
      positionX: 6.5,
      positionY: -5,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [4, 3, 3],
      type: 'obstacle',
    },
    {
      positionX: -4.5,
      positionY: -5,
      positionZ: -300,
      obstacleName: 'WallDoorway',
      scale: [3, 3, 3],
      type: 'doorway',
    },
    {
      positionX: -4.5,
      positionY: 5.2,
      positionZ: -300,
      obstacleName: 'BoxTransparent',
      color: 'blue',
      scale: [6, 4, 3.2],
      type: 'obstacle',
    },
    {
      positionX: -14,
      positionY: -5,
      positionZ: -300,
      obstacleName: 'WallFlat',
      scale: [3, 3, 3],
      type: 'obstacle',
    },
  ],
  //Spikes ---------------------------------------------------------------------------------------
  //2 spike rows (2 left, 2 right)
  [
    {
      positionX: 5,
      positionY: -0.2,
      positionZ: -300,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -300,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: -0.2,
      positionZ: -240,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
      },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -240,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
  
  ],
  //2 spike rows (2 left, 2 right)
  [
    {
      positionX: -5,
      positionY: -0.2,
      positionZ: -300,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -300,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: -0.2,
      positionZ: -240,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
      },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -240,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
  
  ],
  //4 spike rows with yellow gem
  [
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -295,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -290,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -285,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -280,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: -0.2,
      positionZ: -305,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: -0.2,
      positionZ: -300,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: -0.2,
      positionZ: -295,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: -0.2,
      positionZ: -290,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 8,
      positionZ: -295,
      obstacleName: 'YellowGem',
      type: 'yellow-gem',
    },
  
  ],
  //4 spike rows with green gem
  [
    {
      positionX: -5,
      positionY: -0.2,
      positionZ: -295,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: -0.2,
      positionZ: -290,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: -0.2,
      positionZ: -285,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: -0.2,
      positionZ: -280,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -305,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -300,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -295,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -290,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 8,
      positionZ: -295,
      obstacleName: 'GreenGem',
      type: 'green-gem',
    },
  
  ],
  //Two times 3x spike rows (2 jumps)
  [
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -310,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: -0.2,
      positionZ: -310,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -260,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: -0.2,
      positionZ: -260,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: -0.2,
      positionZ: -260,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },

  
  ],
  //Spike patch right wiht coins right
  [
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -295,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -290,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: -0.2,
      positionZ: -295,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: -0.2,
      positionZ: -290,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 4,
      positionZ: -260,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 6,
      positionZ: -268,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 8,
      positionZ: -276,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 9,
      positionZ: -284,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 8,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },

  
  ],
  //Spike patch right wiht coins middle
  [
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -295,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -290,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: -0.2,
      positionZ: -295,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: -0.2,
      positionZ: -290,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 4,
      positionZ: -260,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -268,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 8,
      positionZ: -276,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 9,
      positionZ: -284,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 8,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },

  
  ],
  //Spike patch left wiht coins middle
  [
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -295,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -290,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: -0.2,
      positionZ: -295,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: -0.2,
      positionZ: -290,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 4,
      positionZ: -260,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -268,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 8,
      positionZ: -276,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 9,
      positionZ: -284,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 8,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },

  
  ],
  //Spike patch left wiht coins left
  [
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -295,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: -0.2,
      positionZ: -290,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: -0.2,
      positionZ: -295,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: -0.2,
      positionZ: -290,
      obstacleName: 'Spikes',
      rotation: [0, Math.PI / 1.1, 0],
      type: 'obstacle',
    },
    //jumpcoins
    {
      positionX: -5,
      positionY: 4,
      positionZ: -260,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 6,
      positionZ: -268,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 8,
      positionZ: -276,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 9,
      positionZ: -284,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 8,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },

  
  ],
  //Tables Long ----------------------------------------------------------------------------------
  //Tables in middle (coins right)
  [
    {
      positionX: 0,
      positionY: 0,
      positionZ: -310,
      rotation: [0, 0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_A',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 0,
      positionZ: -300,
      rotation: [0, -0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 0,
      positionZ: -290,
      rotation: [0, 0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -290,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -310,
      obstacleName: 'Coin',
      type: 'coin',
    },

  ],
  //Tables in middle (coins left)
  [
    {
      positionX: 0,
      positionY: 0,
      positionZ: -310,
      rotation: [0, 0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 0,
      positionZ: -300,
      rotation: [0, -0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_B',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 0,
      positionZ: -290,
      rotation: [0, 0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_A',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -290,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -310,
      obstacleName: 'Coin',
      type: 'coin',
    },

  ],
  //Tables right (coins left)
  [
    {
      positionX: 5,
      positionY: 0,
      positionZ: -310,
      rotation: [0, 0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_B',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 0,
      positionZ: -300,
      rotation: [0, -0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 0,
      positionZ: -290,
      rotation: [0, 0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_A',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -290,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -310,
      obstacleName: 'Coin',
      type: 'coin',
    },

  ],
   //Tables right (coins middle)
  [
    {
      positionX: 5,
      positionY: 0,
      positionZ: -310,
      rotation: [0, 0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 0,
      positionZ: -300,
      rotation: [0, -0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 0,
      positionZ: -290,
      rotation: [0, 0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_B',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -290,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -310,
      obstacleName: 'Coin',
      type: 'coin',
    },

  ],
  //Tables left and right
   [
    {
      positionX: 5,
      positionY: 0,
      positionZ: -310,
      rotation: [0, -0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 0,
      positionZ: -300,
      rotation: [0, -0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 0,
      positionZ: -290,
      rotation: [0, 0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_B',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 0,
      positionZ: -310,
      rotation: [0, 0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_A',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 0,
      positionZ: -300,
      rotation: [0, -0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 0,
      positionZ: -290,
      rotation: [0, 0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },

  ],
  //Tables flipped right and left (coins middle)
   [
    {
      positionX: 2,
      positionY: 0,
      positionZ: -310,
      rotation: [0, Math.PI/2, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: -2,
      positionY: 0,
      positionZ: -280,
      rotation: [0, Math.PI/2, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_B',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 4,
      positionZ: -260,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -268,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 8,
      positionZ: -276,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 9,
      positionZ: -284,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 8,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },

  ],
  // Tables flipped left and right (coins middle)
   [
    {
      positionX: -2,
      positionY: 0,
      positionZ: -310,
      rotation: [0, Math.PI/2, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: 2,
      positionY: 0,
      positionZ: -280,
      rotation: [0, Math.PI/2, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_A',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 4,
      positionZ: -260,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -268,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 8,
      positionZ: -276,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 9,
      positionZ: -284,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 8,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },

  ],
  // Tables
   [
    {
      positionX: -2,
      positionY: 0,
      positionZ: -310,
      rotation: [0, Math.PI/2, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: 2,
      positionY: 0,
      positionZ: -280,
      rotation: [0, Math.PI/2, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_A',
      type: 'obstacle',
    },

  ],
  // Tables
   [
    {
      positionX: -2,
      positionY: 0,
      positionZ: -310,
      rotation: [0, Math.PI/2, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_B',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 0,
      positionZ: -280,
      rotation: [0, 0, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 0,
      positionZ: -290,
      rotation: [0, 0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_A',
      type: 'obstacle',
    },

  ],
  // Tables
   [
    {
      positionX: 2,
      positionY: 0,
      positionZ: -310,
      rotation: [0, Math.PI/2, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 0,
      positionZ: -280,
      rotation: [0, 0, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_B',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 0,
      positionZ: -290,
      rotation: [0, 0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },

  ],
  //Tables
  [
    {
      positionX: 0,
      positionY: 0,
      positionZ: -308,
      rotation: [0, 0, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 0,
      positionZ: -272,
      rotation: [0, -0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_A',
      type: 'obstacle',
    },

  ],
  // Tables with green gem
   [
    {
      positionX: -2,
      positionY: 0,
      positionZ: -310,
      rotation: [0, Math.PI/2, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: 2,
      positionY: 0,
      positionZ: -280,
      rotation: [0, Math.PI/2, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_B',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 2.5,
      positionZ: -295,
      obstacleName: 'GreenGem',
      type: 'green-gem',
    },

  ],
  // Tables with blue gem
   [
    {
      positionX: -2,
      positionY: 0,
      positionZ: -310,
      rotation: [0, Math.PI/2, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 0,
      positionZ: -280,
      rotation: [0, 0, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_A',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 0,
      positionZ: -290,
      rotation: [0, 0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 2.5,
      positionZ: -310,
      obstacleName: 'BlueGem',
      type: 'blue-gem',
    },

  ],
  // Tables with yellow gem
   [
    {
      positionX: 2,
      positionY: 0,
      positionZ: -310,
      rotation: [0, Math.PI/2, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 0,
      positionZ: -280,
      rotation: [0, 0, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_B',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 0,
      positionZ: -290,
      rotation: [0, 0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 2.5,
      positionZ: -310,
      obstacleName: 'YellowGem',
      type: 'yellow-gem',
    },

  ],
  //Tables with red gem
  [
    {
      positionX: 0,
      positionY: 0,
      positionZ: -308,
      rotation: [0, 0, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 0,
      positionZ: -272,
      rotation: [0, -0.1, 0],
      obstacleName: 'TableLong',
      typeMesh: 'table_decorated_A',
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 2.5,
      positionZ: -290,
      obstacleName: 'RedGem',
      type: 'red-gem',
    },

  ],
  //Barriers ---------------------------------------------------------------------------------------
  // Barrier right (coin middle)
  [ 
    {
      positionX: 2.5,
      positionY: 2.5,
      positionZ: -290,
      obstacleName: 'Barrier',
      scale: [2.4, 2, 2],
      type: 'obstacle',
    },
    {
      positionX: -2.5,
      positionY: 0,
      positionZ: -290,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 7.5,
      positionY: 0,
      positionZ: -290,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -280,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -310,
      obstacleName: 'Coin',
      type: 'coin',
    },

  ],
    // Barrier right (coin right)
  [ 
    {
      positionX: 2.5,
      positionY: 2.5,
      positionZ: -290,
      obstacleName: 'Barrier',
      scale: [2.4, 2, 2],
      type: 'obstacle',
    },
    {
      positionX: -2.5,
      positionY: 0,
      positionZ: -290,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 7.5,
      positionY: 0,
      positionZ: -290,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -280,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -310,
      obstacleName: 'Coin',
      type: 'coin',
    },

  ],
  // Barrier left (coin middle)
  [ 
    {
      positionX: -2.5,
      positionY: 2.5,
      positionZ: -290,
      obstacleName: 'Barrier',
      scale: [2.4, 2, 2],
      type: 'obstacle',
    },
    {
      positionX: 2.5,
      positionY: 0,
      positionZ: -290,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -7.5,
      positionY: 0,
      positionZ: -290,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -280,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -310,
      obstacleName: 'Coin',
      type: 'coin',
    },

  ],
    // Barrier left (coin right)
  [ 
    {
      positionX: -2.5,
      positionY: 2.5,
      positionZ: -290,
      obstacleName: 'Barrier',
      scale: [2.4, 2, 2],
      type: 'obstacle',
    },
    {
      positionX: 2.5,
      positionY: 0,
      positionZ: -290,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -7.5,
      positionY: 0,
      positionZ: -290,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -280,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -310,
      obstacleName: 'Coin',
      type: 'coin',
    },

  ],
  // 2 barriers met coins
  [ 
    {
      positionX: 2.5,
      positionY: 2.5,
      positionZ: -260,
      obstacleName: 'Barrier',
      scale: [2.4, 2, 2],
      type: 'obstacle',
    },
    {
      positionX: -2.5,
      positionY: 0,
      positionZ: -260,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 7.5,
      positionY: 0,
      positionZ: -260,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -250,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -260,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -270,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -2.5,
      positionY: 2.5,
      positionZ: -310,
      obstacleName: 'Barrier',
      scale: [2.4, 2, 2],
      type: 'obstacle',
    },
    {
      positionX: 2.5,
      positionY: 0,
      positionZ: -310,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -7.5,
      positionY: 0,
      positionZ: -310,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -310,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -320,
      obstacleName: 'Coin',
      type: 'coin',
    },

  ],
  // 2 barriers met coins
  [ 
    {
      positionX: -2.5,
      positionY: 2.5,
      positionZ: -260,
      obstacleName: 'Barrier',
      scale: [2.4, 2, 2],
      type: 'obstacle',
    },
    {
      positionX: 2.5,
      positionY: 0,
      positionZ: -260,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -7.5,
      positionY: 0,
      positionZ: -260,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -250,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -260,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -270,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 2.5,
      positionY: 2.5,
      positionZ: -310,
      obstacleName: 'Barrier',
      scale: [2.4, 2, 2],
      type: 'obstacle',
    },
    {
      positionX: -2.5,
      positionY: 0,
      positionZ: -310,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 7.5,
      positionY: 0,
      positionZ: -310,
      obstacleName: 'Column',
      scale: [1.5, 4, 2],
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -310,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -320,
      obstacleName: 'Coin',
      type: 'coin',
    },

  ],
  // Custom patterns -------------------------------------------------
    // small table and keg gathering
  [
    {
      positionX: 2,
      positionY: 0,
      positionZ: -300,
      rotation: [0, Math.PI/2, 0],  
      obstacleName: 'TableLong',
      typeMesh: 'table_cloth',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 0,
      positionZ: -300,
      rotation: [0, 0, 0],
      obstacleName: 'TableSmall',
      type: 'obstacle',
    },
     {
      positionX: 5,
      positionY: 0,
      positionZ: -293,
      rotation: [0, Math.PI/2.2, 0],
      scale:[2.2, 2.2, 2.2],
      obstacleName: 'Keg',
      typeMesh: 'keg',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 0,
      positionZ: -288,
      rotation: [0, Math.PI/2.2, 0],
      obstacleName: 'Keg',
      typeMesh: 'keg_decorated',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 0,
      positionZ: -288,
      obstacleName: 'Keg',
      typeMesh: 'keg_large',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 0,
      positionZ: -282,
      obstacleName: 'Keg',
      typeMesh: 'keg_large',
      scale:[1.7, 1.7, 1.7],
      type: 'obstacle',
    },

  ],
  //small boxes gathering
  [
    {
      positionX: 0,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'Boxes',
      typeMesh: 'box_crates',
      type: 'obstacle',
    },
    {
      positionX: -5,
      positionY: 0,
      positionZ: -310,
      obstacleName: 'Boxes',
      scale:[1.5, 1.5, 1.5],
      typeMesh: 'box_stacked',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 0,
      positionZ: -280,
      rotation: [0, 0.2, 0],
      obstacleName: 'BoxLarge',
      type: 'obstacle',
    },
    {
      positionX: 5,
      positionY: 0,
      positionZ: -275,
      rotation: [0, -0.2, 0],
      scale:[1.5, 1.5, 1.5],
      obstacleName: 'BoxLarge',
      type: 'obstacle',
    },

  ],
  // Coins -----------------------------------------------------------------------------------
  // coin pattern left
  [
     {
      positionX: -5,
      positionY: 2,
      positionZ: -254,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 4,
      positionZ: -260,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 6,
      positionZ: -268,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 8,
      positionZ: -276,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 9,
      positionZ: -284,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 8,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 2,
      positionZ: -306,
      obstacleName: 'Coin',
      type: 'coin',
    },

  ],
  // coin pattern right
  [
    {
      positionX: 5,
      positionY: 2,
      positionZ: -254,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 4,
      positionZ: -260,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 6,
      positionZ: -268,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 8,
      positionZ: -276,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 9,
      positionZ: -284,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 8,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 2,
      positionZ: -306,
      obstacleName: 'Coin',
      type: 'coin',
    },

  ],
  // coin pattern center
  [
    {
      positionX: 0,
      positionY: 2,
      positionZ: -254,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 4,
      positionZ: -260,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -268,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 8,
      positionZ: -276,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 9,
      positionZ: -284,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 8,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 2,
      positionZ: -306,
      obstacleName: 'Coin',
      type: 'coin',
    },
  ],
  // coin pattern ground
  [
    {
      positionX: 0,
      positionY: 1,
      positionZ: -284,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -308,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -316,
      obstacleName: 'Coin',
      type: 'coin',
    },

    {
      positionX: -5,
      positionY: 1,
      positionZ: -294,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -302,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -310,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -318,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -326,
      obstacleName: 'Coin',
      type: 'coin',
    },

    {
      positionX: 5,
      positionY: 1,
      positionZ: -274,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -282,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -290,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -298,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -306,
      obstacleName: 'Coin',
      type: 'coin',
    },
  ],
  [
    {
      positionX: 0,
      positionY: 1,
      positionZ: -284,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -308,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 1,
      positionZ: -316,
      obstacleName: 'Coin',
      type: 'coin',
    },

    {
      positionX: 5,
      positionY: 1,
      positionZ: -294,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -302,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -310,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -318,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 1,
      positionZ: -326,
      obstacleName: 'Coin',
      type: 'coin',
    },

    {
      positionX: -5,
      positionY: 1,
      positionZ: -274,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -282,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -290,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -298,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 1,
      positionZ: -306,
      obstacleName: 'Coin',
      type: 'coin',
    },
  ],
  //Rubble -----------------------------------------------------------------------------------
  // Rubble (coin middle)
  [
    {
      positionX: 0,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'Rubble',
      scale: [2, 1.2, 2],
      type: 'rubble',
    },
    {
      positionX: 0,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'BoxTransparent',
      scale: [14, 6.5, 4],
      color: 'blue',
      type: 'obstacle',
    },
     {
      positionX: 0,
      positionY: 2,
      positionZ: -274,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 4,
      positionZ: -278,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -286,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 8,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 9,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 8,
      positionZ: -308,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 6,
      positionZ: -316,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 0,
      positionY: 2,
      positionZ: -320,
      obstacleName: 'Coin',
      type: 'coin',
    },
  ],
  // rubble (coin right)
  [
    {
      positionX: 0,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'Rubble',
      scale: [2, 1.2, 2],
      type: 'rubble',
    },
    {
      positionX: 0,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'BoxTransparent',
      scale: [14, 6.5, 4],
      color: 'blue',
      type: 'obstacle',
    },
     {
      positionX: 5,
      positionY: 2,
      positionZ: -274,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 4,
      positionZ: -278,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 6,
      positionZ: -286,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 8,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 9,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 8,
      positionZ: -308,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 6,
      positionZ: -316,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: 5,
      positionY: 2,
      positionZ: -320,
      obstacleName: 'Coin',
      type: 'coin',
    },
  ],
  // rubble (coin left)
  [
    {
      positionX: 0,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'Rubble',
      scale: [2, 1.2, 2],
      type: 'rubble',
    },
    {
      positionX: 0,
      positionY: 0,
      positionZ: -300,
      obstacleName: 'BoxTransparent',
      scale: [14, 6.5, 4],
      color: 'blue',
      type: 'obstacle',
    },
     {
      positionX: -5,
      positionY: 2,
      positionZ: -274,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 4,
      positionZ: -278,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 6,
      positionZ: -286,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 8,
      positionZ: -292,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 9,
      positionZ: -300,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 8,
      positionZ: -308,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 6,
      positionZ: -316,
      obstacleName: 'Coin',
      type: 'coin',
    },
    {
      positionX: -5,
      positionY: 2,
      positionZ: -320,
      obstacleName: 'Coin',
      type: 'coin',
    },
  ],
];

export default patterns1;